**### Practice Question With data Sheet**

In [2]:
import numpy as np

scores = np.array([
    [85, 90, 78],
    [88, 76, 92],
    [90, 89, 85],
    [70, 80, 75],
    [95, 92, 98]
])

In [35]:
print("1. Shape of scores array: ", scores.shape)
print("2. The total number of elements in scores: ", scores.size)
print("3. Score of the First student: ", scores[0,0])
print("4. Exact marks of the third subject for all students: ", scores[:,2])

avg_Score_Student = np.mean(scores, axis=1)
avg_score_subject = np.mean(scores, axis=0)
print("5. The average marks of Each student: ", avg_Score_Student)
print("6. The average marks of Each stubject: ", avg_score_subject)

print("7. lowest marks in entire dataset: ", np.min(scores))
print("8. Highest marks in entire dataset: ", np.max(scores))

high_scorers = avg_Score_Student > 85
students = np.where(avg_Score_Student > 85)
print("9. Students with average score grater than 85", students)

a = scores + 5 
print("10. Added 5  grace marks to each score:\n", a )

scores[scores<80] = 80
print("11. Replaced marks less than 80 with 80: ", scores)

print("12. Standard deviation of scores: ", np.std(scores))

sorted_marks = np.sort(scores[1])
print("13. Sorting the marks of thr second student: ",sorted_marks)


flat = scores.flatten()
print("14. Flattened the array: ", flat)

count_score_90 = np.sum(scores > 90)
print("15. count of scores more than 90: ", count_score_90 )

# Extra Questions 

Max_Marks = np.argmax(scores)
print("16. index containing maximum marks: ", Max_Marks)


sum1 = np.sum(scores, axis=1)
sum2 = np.sum(scores, axis=0)
print("17. sum of marks for each student: ", sum1)
print("18. sum of marks for each subject: ", sum2)




1. Shape of scores array:  (5, 3)
2. The total number of elements in scores:  15
3. Score of the First student:  85
4. Exact marks of the third subject for all students:  [80 92 85 80 98]
5. The average marks of Each student:  [85.         86.66666667 88.         80.         95.        ]
6. The average marks of Each stubject:  [87.6 86.2 87. ]
7. lowest marks in entire dataset:  80
8. Highest marks in entire dataset:  98
9. Students with average score grater than 85 (array([1, 2, 4]),)
10. Added 5  grace marks to each score:
 [[ 90  95  85]
 [ 93  85  97]
 [ 95  94  90]
 [ 85  85  85]
 [100  97 103]]
11. Replaced marks less than 80 with 80:  [[85 90 80]
 [88 80 92]
 [90 89 85]
 [80 80 80]
 [95 92 98]]
12. Standard deviation of scores:  5.836284967530477
13. Sorting the marks of thr second student:  [80 88 92]
14. Flattened the array:  [85 90 80 88 80 92 90 89 85 80 80 80 95 92 98]
15. count of scores more than 90:  4
16. index containing maximum marks:  14
17. sum of marks for each stu